### ISSUE TITLE
Error Drawing Pieces

### ISSUE THREAD

**Issue by grafton-legare** [marcusbuffett/command-line-chess#56] opened 2023-05-05 19:57 UTC
I just installed the game for the first time (5/5/23), and when I start a new game, it never draws the pieces in row 8, i.e. black's non-pawn pieces. It also never draws those pieces as the game continues. Note, I am on Windows 11 currently.
![image_2023-05-05_155738231](https://user-images.githubusercontent.com/122751288/236557332-27809111-bc6f-45ea-ad01-476cdd8bef4c.png)

**Comment by ClasherKasten** [comment] 2023-05-06 09:19
duplicate of #53

You have a black background and black pieces per default get drawn in a black color onto the screen (the same problem exists with white pieces, see issue linked). Try to use the `--checkered`/`-c` option which enables drawing a chess-field behind the pieces or change the color of the black pieces through `--black`/`-b`. This should be enough contrast then to see the black pieces.

**Closed by ClasherKasten** 2023-05-06 09:19 UTC
